### ISSUE TITLE
1. Literature search

### ISSUE THREAD

**Issue by MaxenceOuafik** [Asrahal/MSM-Syndemic-Scoping-Review#1]
The literature search part is done, alongside the PRISMA flowchart ; feel free to comment anytime you want
https://github.com/Asrahal/MSM-Syndemic-Scoping-Review/blob/b09d2451ea92352591e6f44fd480083156bf200d/Output/Literature%20search.docx

**Comment by BeaScholtes** [comment]
Here are my comments on the literature search section
[1 - Literature search bs comments.docx](https://github.com/Asrahal/MSM-Syndemic-Scoping-Review/files/6383964/1.-.Literature.search.bs.comments.docx)
