### ISSUE TITLE
2.1 General characteristics of included studies

### ISSUE THREAD

**Issue by MaxenceOuafik** [Asrahal/MSM-Syndemic-Scoping-Review#2]
This part, where design, location, sample size and age are summarized is completed. Do you think it's clear enough ? What do you think of the plot ?

**Comment by BeaScholtes** [comment]
Hello, 

Here is the first draft document with my comments. 

Hope all is clear - they are only minor points.

thanks 

[First draft bs comments.docx](https://github.com/Asrahal/MSM-Syndemic-Scoping-Review/files/6383828/First.draft.bs.comments.docx)
